#!/bin/bash

# Usage: use dotenv [<file>] [--root=<root>] [--overwrite]
#
# Examples:
#   use dotenv .env
#   use dotenv --root=./src
#   use dotenv --overwrite
use_dotenv() {

  log_debug "use dotenv $*"

  # parse args

  local root=$PWD
  local overwrite=0

  local args
  if ! args=$(getopt -o r:,o --long root:,overwrite -- "$@"); then
    log_warn "invalid options provided: $*"
  else
    eval set -- "$args"
    while true; do
      case "$1" in

        -r | --root)
          shift
          root=$1
          ;;

        -o | --overwrite)
          overwrite=1
          ;;

        --)
          shift
          break
          ;;

      esac
      shift
    done
  fi

  local file=${1:-.env}

  # handle

  local prev_env
  prev_env=$(declare -p -x | sed 's/^declare -x/declare -g -x/')

  pushd "$root" >/dev/null || return 1

  if [ -f "$file" ]; then

    log_debug "loading ${root}/${file}"

    set -o allexport
    \. "$file" || return 1
    set +o allexport

    watch_file "$file"

  fi

  popd >/dev/null || return 1

  if [ "$overwrite" = 0 ]; then
    eval "$prev_env" || return 1
  fi

  log_debug exit

}
