#!/bin/bash

# Usage: use dotenv <file> [--overwrite]
#
# Examples:
#   use dotenv .env
#   use dotenv .env --overwrite
use_dotenv() {

  log_debug "use dotenv $*"

  # parse args

  local overwrite=0

  local args
  if ! args=$(getopt -o o --long overwrite -- "$@"); then
    log_warn "invalid options provided: $*"
  else
    eval set -- "$args"
    while true; do
      case "$1" in

        -o | --overwrite)
          overwrite=1
          ;;

        --)
          shift
          break
          ;;

      esac
      shift
    done
  fi

  local file=${1:-.env}

  # handle

  local prev_env
  prev_env=$(declare -p -x)

  if [ -f "$file" ]; then

    set -o allexport
    \. "$file" || return 1
    set +o allexport

    watch_file "$file"

  fi

  if [ "$overwrite" = 0 ]; then
    eval "$prev_env"
  fi

  log_debug exit

}
