#!/bin/bash

# Usage: use node [<version>] [--root=<root>]
#
# Examples:
#   use node
#   use node 18
#   use node --root=./src
use_node() {

  log_debug "use node $*"

  # parse args

  local root=$PWD

  local args
  if ! args=$(getopt -o r: --long root: -- "$@"); then
    log_warn "invalid options provided: $*"
  else
    eval set -- "$args"
    while true; do
      case "$1" in

      -r | --root)
        shift
        root=$1
        ;;

      --)
        shift
        break
        ;;

      esac
      shift
    done
  fi

  local version=${1:-} # defaults to read from .nvmrc

  # handle

  pushd "$root" >/dev/null || return 1

  watch_file package.json
  watch_file yarn.lock
  watch_file package-lock.json

  _use_node "$version"
  local code=$?

  popd >/dev/null || return 1

  log_debug exit
  return "$code"

}

_use_node() {

  local version=$1

  _activate_nvm || return 1
  _activate_node "$version" || return 1
  _install_node_dependencies || return 0

}

# nvm
# --------------------------------------------------------------------------------------------------

_activate_nvm() {

  log_debug "activating nvm"

  if has nvm; then
    return 0
  fi

  local nvm_dir=~/.nvm
  local nvm_sh=$nvm_dir/nvm.sh

  if [ ! -f "$nvm_sh" ]; then
    _install_nvm || return 1
  fi

  if [ -z "$NVM_DIR" ]; then
    export NVM_DIR=$nvm_dir
  fi

  \. "$nvm_sh" || return 1

  log_debug "activated nvm"

}

_install_nvm() {

  log_info "installing nvm"

  curl -s https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash || return 1

  log_debug "installed nvm"

}

_upgrade_nvm() {

  log_info "upgrading nvm"

  local root=$NVM_DIR

  (

    cd "$root" || return 1

    # checkout latest version tag

    git fetch --quiet --tags origin || return 1
    hash=$(git rev-list --tags --max-count=1) || return 1
    version=$(git describe --abbrev=0 --tags --match "v[0-9]*" "$hash") || return 1

    git checkout --quiet "$version" || return 1

  ) || return 1

  log_debug "upgraded nvm"

}

# node
# --------------------------------------------------------------------------------------------------

_activate_node() {

  local version=$1

  log_debug "activating node.js"

  nvm use --silent "$version" >/dev/null
  local code=$?

  if [ "$code" = 3 ]; then

    _install_node "$version" || return 1

  elif [ "$code" != 0 ]; then

    log_error "failed to activate node.js"
    return 1

  fi

  log_debug "activated node.js"

}

_install_node() {

  local version=$1

  log_info "installing node.js"

  # check if there's already a default node.js version
  local default
  default=$(nvm alias default >/dev/null)

  nvm install "$version" >/dev/null || return 1

  nvm exec "$version" \
    npm --silent --no-audit --no-fund \
    install --global \
    npm yarn ||
    return 1

  # nvm makes the first installed version the default one
  if [ -z "$default" ]; then
    nvm unalias default >/dev/null || return 1
  fi

  log_debug "installed node.js"

}

# deps
# --------------------------------------------------------------------------------------------------

_install_node_dependencies() {

  if [ -f yarn.lock ]; then

    if ! has yarn; then
      _npm_install --global yarn || return 1
    fi

    _handle_install_node_dependencies yarn \
      _yarn_install --pure-lockfile ||
      return 1

  elif [ -f package-lock.json ]; then

    _handle_install_node_dependencies npm \
      _npm_install || return 1

  elif [ -f package.json ]; then

    if ! has yarn; then
      _npm_install --global yarn || return 1
    fi

    _handle_install_node_dependencies yarn \
      _yarn_install ||
      return 1

  fi

}

_handle_install_node_dependencies() {

  local type=$1
  shift

  log_info "restoring $type dependencies"

  "$@"
  local code=$?

  if [ "$code" != 0 ]; then
    log_error "failed to restore $type dependencies"
    return 1
  fi

  log_debug "restored $type dependencies"

}

_npm_install() {

  NPM_CONFIG_ENGINE_STRICT=true \
    npm install \
    --silent \
    --no-audit \
    --no-fund \
    "$@" \
    >/dev/null ||
    return 1

}

_yarn_install() {

  NPM_CONFIG_ENGINE_STRICT=true \
    yarn install \
    --silent \
    --non-interactive \
    --no-progress \
    --prefer-offline \
    --no-node-version-check \
    --pure-lockfile \
    "$@" \
    >/dev/null ||
    return 1

}
