#!/bin/bash

is_fresh() {

  local path

  for path in "$@"; do
    if [ -f "$path" ]; then
      __cache__is_fresh__ "$path" || return 1
    fi
  done

  return 0

}

add_to_cache() {

  local path

  for path in "$@"; do
    if [ -f "$path" ]; then
      __cache__add__ "$path" || return 1
    else
      __cache__remove__ "$path" || return 1
    fi
  done

}

remove_from_cache() {

  local path

  for path in "$@"; do
    __cache__remove__ "$path" || return 1
  done

}

__cache__is_fresh__() {

  local path_live
  local path_cache
  local hash_cache
  local hash_live
  local date_now
  local date_cache

  path_live=$(realpath "$1") || return 1
  path_cache=$(__cache__get_path__ "$path_live") || return 1

  hash_live=$(__cache__get_hash__ "$path_live") || return 1
  hash_cache=$(__cache__get_hash__ "$path_cache") || return 1

  date_now=$(date +%s) || return 1
  date_cache=$(__cache__get_last_modification_time__ "$path_cache") || return 1

  if [ "$hash_cache" != "$hash_live" ]; then
    return 1
  fi

  if [ "$((date_now - date_cache))" -gt "$((7 * 24 * 60 * 60))" ]; then
    return 1
  fi

  return 0

}

__cache__add__() {

  local path
  local dir

  path=$(__cache__get_path__ "$1") || return 1
  dir=$(dirname "$path") || return 1

  mkdir -p "$dir" || return 1
  __cache__get_hash__ "$1" >"$path" || return 1

}

__cache__remove__() {

  local path
  path=$(__cache__get_path__ "$1") || return 1

  rm -rf "$path" >/dev/null

}

__cache__get_path__() {

  local path
  path=$(realpath "$1") || return 1
  path=${path#/}
  path=${path%/}

  echo "${HOME}/.cache/profile.d/plugins/direnv/${path}"

}

__cache__get_hash__() {

  if [[ $1 == "${HOME}/.cache/profile.d/plugins/direnv/"* ]]; then
    cat "$1" 2>/dev/null
  else
    sha256sum <"$1"
  fi

}

__cache__get_last_modification_time__() {

  stat -c %Y "$1"

}
