#!/bin/bash

log_status() {
  log_info "$@" # see ./log
}

use() {
  __overrides__dispatch__ use "$@" || return 1
}

layout() {
  __overrides__dispatch__ layout "$@" || return 1
}

__overrides__dispatch__() {

  local command=$1
  shift

  local handler=$1
  shift

  # set current command & handler

  local prev_command=$__PROFILE_D_DIRENV_COMMAND__
  local prev_handler=$__PROFILE_D_DIRENV_HANDLER__

  export __PROFILE_D_DIRENV_COMMAND__=$command
  export __PROFILE_D_DIRENV_HANDLER__=$handler

  # dispatch

  log_debug enter

  "${command}_${handler}" "$@"
  local code=$?

  log_debug exit

  # restore previous command & handler

  if [ -n "$prev_command" ]; then
    export __PROFILE_D_DIRENV_COMMAND__=$prev_command
  else
    unset __PROFILE_D_DIRENV_COMMAND__
  fi

  if [ -n "$prev_handler" ]; then
    export __PROFILE_D_DIRENV_HANDLER__=$prev_handler
  else
    unset __PROFILE_D_DIRENV_HANDLER__
  fi

  return "$code"

}
