#!/bin/bash

use() {
  _dispatch use "$@" || return 1
}

layout() {
  _dispatch layout "$@" || return 1
}

_dispatch() {

  local command=$1
  shift

  local handler=$1
  shift

  # set current command & handler

  local prev_command=$__PROFILE_D_DIRENV_COMMAND__
  local prev_handler=$__PROFILE_D_DIRENV_HANDLER__

  export __PROFILE_D_DIRENV_COMMAND__=$command
  export __PROFILE_D_DIRENV_HANDLER__=$handler

  # dispatch

  "${command}_${handler}" "$@"
  local code=$?

  # revert previous command & handler

  if [ -n "$prev_command" ]; then
    export __PROFILE_D_DIRENV_COMMAND__=$prev_command
  else
    unset __PROFILE_D_DIRENV_COMMAND__
  fi

  if [ -n "$prev_handler" ]; then
    export __PROFILE_D_DIRENV_HANDLER__=$prev_handler
  else
    unset __PROFILE_D_DIRENV_HANDLER__
  fi

  return "$code"

}

log_status() {
  log_info "$@" # see ./log
}
